### PR TITLE
Issue 157 resolving support ticket form

### LINKED ISSUE #157: Resolving Support Ticket Form
# Summary

The support ticket resolution form needs to save "closer_notes" and be updated to match InKind styling (the mockup).

# Criteria for Completion
 - [ ] Clicking "Cancel" in this form redirects the user back to the Tickets index page (currently broken)
 - [ ] Clicking "Resolve" in this form saves the notes left by the reviewer/resolver & updates the `support_ticket`'s `closed_at` & `closer_id` fields.
 - [ ] The new form looks like the attached form mockup.
 - [ ] When clicking to view a "closed" support ticket, the view matches the 2nd attached mockup.

## What it looks like now:

Screen Shot 2021-11-28 at 1 59 36 PM

## What an unresolved (open) support_ticket form will look like after this change:

Notes: 

- "Created By" volunteer should not be a link. Just regular text.
- The "Support Request" text under the requestor's name should be dynamic. It should be something like`"#{category} Request", where category is the `support_ticket.category`. Where `survey_response` => "Support", `admin` => "Admin", and `contact_info` => "Contact".
- "Student" is the student associated with the related survey_response. These only exist on "Support" Type tickets as well. If there is no survey_response on the ticket, this field will be left blank.
- "Staff Contact" is the name of the active staff contact associated with the student (for "Support" type tickets). If the requestor IS an admin, the staff contact shows the admin name again (admin == staff). If it's a "Contact" type, drop in the name(s) of the volunteer's students' active staff contact. This will likely only be one name, but could be more that one.

Screen Shot 2021-11-28 at 2 00 11 PM

## What a resolved (closed) support_ticket will look like after this change:

Notes:

"View Tickets" button just links back to the support_tickets index.

Screen Shot 2021-11-28 at 2 00 24 PM

### PR DESCRIPTION
**Pull request by goromlagche**
Resolves #157  

### Description

- Include summary of change and what issue is fixed, including relevant motivation and context.
 [x] Clicking "Cancel" in this form redirects the user back to the Tickets index page (currently broken)
 [x] Clicking "Resolve" in this form saves the notes left by the reviewer/resolver & updates the support_ticket's closed_at & closer_id fields.
 [x] The new form looks like the attached form mockup.
 [x] When clicking to view a "closed" support ticket, the view matches the 2nd attached mockup.
- Explain the need for any added dependencies for this change. (gems, js libraries, etc.)
No dependencies.
- How have you tested this?
I have done manual testing for this, screenshot attached.
I have added one test for adding closer_notes.
I did not find any existing view specific tests. I am not sure if we write feature specs on this project
- Anything else we should know about?
Please review the view changes carefully. I am not familiar with the design practices for this project
### Type of change

* New feature (non-breaking change which adds functionality)

### Screenshots

ISSUE_157

### CODE REVIEW

File: app/controllers/admin/tickets_controller.rb [hunk 1]
```diff
@@ -34,22 +34,34 @@ def create
...
-      @ticket = SupportTicket.find(params[:id])
+      ticket
     end
 
     def resolve
-      @ticket = SupportTicket.find(params[:id])
+      ticket.update ticket_update_params.merge(closed_at: Time.zone.now)
 
-      if @ticket.close!(current_user)
+      if ticket.close!(current_user)
```
Comment (garettarrowood) [inline app/controllers/admin/tickets_controller.rb:43]: Looks like `close!` is already setting the `closed_at` time. Instead of updating the ticket twice, you might try passing the `closer` (current_user) and the `closer_notes` to the `close!` method.

File: app/controllers/admin/tickets_controller.rb [hunk 2]
```diff
@@ -34,22 +34,34 @@ def create
     end
 
     def show
-      @ticket = SupportTicket.find(params[:id])
+      ticket
```
Comment (garettarrowood) [inline app/controllers/admin/tickets_controller.rb:37]: This might be better as a `before_action` for the `show` and `resolve` actions.

**Comment by garettarrowood** [comment]
New HTML looks good. Nice work!

There are a couple small differences from the mock that I think we can still sort out in this change. 
1. Looks like the top top cards on the mock do not have any space between them. 
2. There is a "Resolution Description" caption above the `closer_notes` text area on the mock.

It also seems like we need to change the default background color to a very light shade. Feel free to add that in here, or not. We can add that separately since it looks like it should universally be the background shade on all pages.

**Comment by garettarrowood** [comment]
I'll actually take it from here. This is a great addition already. I will touch up the styles/colors.

Thank you for this contribution!

**Comment by goromlagche** [comment]
@garettarrowood apologies for the delay in response. I see you have a PR for the style changes. I can make a separate PR with the two changes you have requested.

File: app/controllers/admin/tickets_controller.rb (hunk 2 above)
Comment (goromlagche) [reply app/controllers/admin/tickets_controller.rb:37]: resolved in https://github.com/rubyforgood/inkind-admin/pull/183

File: app/controllers/admin/tickets_controller.rb (hunk 1 above)
Comment (goromlagche) [reply app/controllers/admin/tickets_controller.rb:43]: resolved in https://github.com/rubyforgood/inkind-admin/pull/183

**Comment by garettarrowood** [comment]
@goromlagche - No worries in anyway at all! I just happen to have some time this morning, and it sounded fun to mess around :).
